name: PanVK

on:
  push:
    paths:
      - "CHANGELOGS.md"

  workflow_dispatch:

permissions:
  contents: write

env:
  API_VER: 35
  BUILD_VARIANT: p2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build script
        run: |
         sudo apt update && bash Build-PanVK.sh

      - name: Debug zip output
        run: |
          find turnip_workdir -type f -name "*.zip" -print

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: turnip-build
          path: pan_workdir/mesa/build/src/panfrost/vulkan/*.zip
          if-no-files-found: error
